language: ruby
sudo: false

cache:
  bundler: true
  directories:
    - node_modules

rvm:
  - "2.2.3"

before_script:
  - "npm install --no-bin-links"
  - "cp -fv preprocessor.modified.js node_modules/karma/lib/preprocessor.js"

script:
  - "bundle exec rake"
