language: ruby
sudo: false

cache:
  bundler: true
  directories:
    - node_modules

rvm:
  - "2.2.4"

before_script:
  - "nvm install"
  - "nvm use"
  - "node -v"
  - "npm install --no-bin-links"

script:
  - "bundle exec rake"
